[package]
name = "binjs_shared"
version = "0.1.1"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[dependencies]
downcast-rs = "^1.0"
itertools = "^0.7"
serde_json = { version = "^1.0.38", features = ["unbounded_depth"] }
log = "^0.4"
serde = { version = "^1.0", features = ["derive"] }
