[package]
name = "binjs_shared"
version = "0.1.1"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[dependencies]
downcast-rs = "^1.0"
itertools = "^0.7"
json = "^0.11"
log = "^0.4"
serde = { version = "^1.0", features = ["derive"] }
